### PR TITLE
Implement Google Authentication. Merge conflicts with master.

### PR DESCRIPTION
**Pull request by johnbwoodruff**
Also updated name of controller being imported into routes to be less confusing with model name.

### CODE REVIEW

**Comment by johnbwoodruff** [comment]
@drewctate @mountain01 @sttracy4 @gshigeto I know the build is failing, it has to do with the `.env` file that is not committed for obvious reasons. I'm working on a solution for that. For now, go through the changes, ask questions, comment, approve etc.

**Comment by gshigeto** [comment]
👍

**Comment by johnbwoodruff** [comment]
Making a few updates to this pull request, I'll comment again when I need review.

**Comment by johnbwoodruff** [comment]
@gshigeto @drewctate @mountain01 @sttracy4 It is now ready to be fully code reviewed!!!

**Comment by mountain01** [comment]
👍 It looks good to me

**Pull request merged**
